// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Iq.pb.h"
#import "Presence.pb.h"
#import "Message.pb.h"
// @@protoc_insertion_point(imports)

@class IqAction;
@class IqActionBuilder;
@class IqActionResponse;
@class IqActionResponseBuilder;
@class IqPacket;
@class IqPacketBuilder;
@class LoginAction;
@class LoginActionBuilder;
@class LoginResponse;
@class LoginResponseBuilder;
@class MessageBody;
@class MessageBodyBuilder;
@class MessagePacket;
@class MessagePacketBuilder;
@class Packet;
@class PacketBuilder;
@class PresencePacket;
@class PresencePacketBuilder;
@class PushNotice;
@class PushNoticeBuilder;
@class ServerNodesPush;
@class ServerNodesPushBuilder;
@class StDLoginAction;
@class StDLoginActionBuilder;
@class StDLoginResponse;
@class StDLoginResponseBuilder;
@class StSLoginAction;
@class StSLoginActionBuilder;
@class StSLoginResponse;
@class StSLoginResponseBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface BasePacketRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Packet : PBGeneratedMessage {
@private
  BOOL hasFrom_:1;
  BOOL hasTo_:1;
  BOOL hasError_:1;
  BOOL hasIq_:1;
  BOOL hasPresence_:1;
  BOOL hasMessage_:1;
  NSString* from;
  NSString* to;
  NSString* error;
  IqPacket* iq;
  PresencePacket* presence;
  MessagePacket* message;
}
- (BOOL) hasFrom;
- (BOOL) hasTo;
- (BOOL) hasError;
- (BOOL) hasIq;
- (BOOL) hasPresence;
- (BOOL) hasMessage;
@property (readonly, strong) NSString* from;
@property (readonly, strong) NSString* to;
@property (readonly, strong) NSString* error;
@property (readonly, strong) IqPacket* iq;
@property (readonly, strong) PresencePacket* presence;
@property (readonly, strong) MessagePacket* message;

+ (Packet*) defaultInstance;
- (Packet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PacketBuilder*) builder;
+ (PacketBuilder*) builder;
+ (PacketBuilder*) builderWithPrototype:(Packet*) prototype;
- (PacketBuilder*) toBuilder;

+ (Packet*) parseFromData:(NSData*) data;
+ (Packet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Packet*) parseFromInputStream:(NSInputStream*) input;
+ (Packet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Packet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Packet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PacketBuilder : PBGeneratedMessageBuilder {
@private
  Packet* result;
}

- (Packet*) defaultInstance;

- (PacketBuilder*) clear;
- (PacketBuilder*) clone;

- (Packet*) build;
- (Packet*) buildPartial;

- (PacketBuilder*) mergeFrom:(Packet*) other;
- (PacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFrom;
- (NSString*) from;
- (PacketBuilder*) setFrom:(NSString*) value;
- (PacketBuilder*) clearFrom;

- (BOOL) hasTo;
- (NSString*) to;
- (PacketBuilder*) setTo:(NSString*) value;
- (PacketBuilder*) clearTo;

- (BOOL) hasError;
- (NSString*) error;
- (PacketBuilder*) setError:(NSString*) value;
- (PacketBuilder*) clearError;

- (BOOL) hasIq;
- (IqPacket*) iq;
- (PacketBuilder*) setIq:(IqPacket*) value;
- (PacketBuilder*) setIqBuilder:(IqPacketBuilder*) builderForValue;
- (PacketBuilder*) mergeIq:(IqPacket*) value;
- (PacketBuilder*) clearIq;

- (BOOL) hasPresence;
- (PresencePacket*) presence;
- (PacketBuilder*) setPresence:(PresencePacket*) value;
- (PacketBuilder*) setPresenceBuilder:(PresencePacketBuilder*) builderForValue;
- (PacketBuilder*) mergePresence:(PresencePacket*) value;
- (PacketBuilder*) clearPresence;

- (BOOL) hasMessage;
- (MessagePacket*) message;
- (PacketBuilder*) setMessage:(MessagePacket*) value;
- (PacketBuilder*) setMessageBuilder:(MessagePacketBuilder*) builderForValue;
- (PacketBuilder*) mergeMessage:(MessagePacket*) value;
- (PacketBuilder*) clearMessage;
@end


// @@protoc_insertion_point(global_scope)
