// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class PresencePacket;
@class PresencePacketBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, PresenceType) {
  PresenceTypeOnLine = 0,
  PresenceTypeOffLine = 1,
  PresenceTypeLeave = 2,
  PresenceTypeBusy = 3,
  PresenceTypeDnd = 4,
  PresenceTypeCallMe = 5,
};

BOOL PresenceTypeIsValidValue(PresenceType value);

typedef NS_ENUM(SInt32, PresenceAtionType) {
  PresenceAtionTypeAgreement = 0,
  PresenceAtionTypeDenial = 1,
  PresenceAtionTypeAdd = 2,
  PresenceAtionTypeRemove = 3,
  PresenceAtionTypeQuery = 4,
  PresenceAtionTypeUpdate = 5,
};

BOOL PresenceAtionTypeIsValidValue(PresenceAtionType value);

typedef NS_ENUM(SInt32, PresenceObjectType) {
  PresenceObjectTypeFriend = 0,
  PresenceObjectTypeGroup = 1,
};

BOOL PresenceObjectTypeIsValidValue(PresenceObjectType value);


@interface PresenceRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PresencePacket : PBGeneratedMessage {
@private
  BOOL hasDescription_:1;
  BOOL hasObjecttype_:1;
  BOOL hasActiontype_:1;
  BOOL hasPresencetype_:1;
  NSString* description;
  PresenceObjectType objecttype;
  PresenceAtionType actiontype;
  PresenceType presencetype;
}
- (BOOL) hasObjecttype;
- (BOOL) hasActiontype;
- (BOOL) hasPresencetype;
- (BOOL) hasDescription;
@property (readonly) PresenceObjectType objecttype;
@property (readonly) PresenceAtionType actiontype;
@property (readonly) PresenceType presencetype;
@property (readonly, strong) NSString* description;

+ (PresencePacket*) defaultInstance;
- (PresencePacket*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PresencePacketBuilder*) builder;
+ (PresencePacketBuilder*) builder;
+ (PresencePacketBuilder*) builderWithPrototype:(PresencePacket*) prototype;
- (PresencePacketBuilder*) toBuilder;

+ (PresencePacket*) parseFromData:(NSData*) data;
+ (PresencePacket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PresencePacket*) parseFromInputStream:(NSInputStream*) input;
+ (PresencePacket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PresencePacket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PresencePacket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PresencePacketBuilder : PBGeneratedMessageBuilder {
@private
  PresencePacket* result;
}

- (PresencePacket*) defaultInstance;

- (PresencePacketBuilder*) clear;
- (PresencePacketBuilder*) clone;

- (PresencePacket*) build;
- (PresencePacket*) buildPartial;

- (PresencePacketBuilder*) mergeFrom:(PresencePacket*) other;
- (PresencePacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PresencePacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasObjecttype;
- (PresenceObjectType) objecttype;
- (PresencePacketBuilder*) setObjecttype:(PresenceObjectType) value;
- (PresencePacketBuilder*) clearObjecttype;

- (BOOL) hasActiontype;
- (PresenceAtionType) actiontype;
- (PresencePacketBuilder*) setActiontype:(PresenceAtionType) value;
- (PresencePacketBuilder*) clearActiontype;

- (BOOL) hasPresencetype;
- (PresenceType) presencetype;
- (PresencePacketBuilder*) setPresencetype:(PresenceType) value;
- (PresencePacketBuilder*) clearPresencetype;

- (BOOL) hasDescription;
- (NSString*) description;
- (PresencePacketBuilder*) setDescription:(NSString*) value;
- (PresencePacketBuilder*) clearDescription;
@end


// @@protoc_insertion_point(global_scope)
