// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Presence.pb.h"
// @@protoc_insertion_point(imports)

@implementation PresenceRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PresenceRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL PresenceTypeIsValidValue(PresenceType value) {
  switch (value) {
    case PresenceTypeOnLine:
    case PresenceTypeOffLine:
    case PresenceTypeLeave:
    case PresenceTypeBusy:
    case PresenceTypeDnd:
    case PresenceTypeCallMe:
      return YES;
    default:
      return NO;
  }
}
BOOL PresenceAtionTypeIsValidValue(PresenceAtionType value) {
  switch (value) {
    case PresenceAtionTypeAgreement:
    case PresenceAtionTypeDenial:
    case PresenceAtionTypeAdd:
    case PresenceAtionTypeRemove:
    case PresenceAtionTypeQuery:
    case PresenceAtionTypeUpdate:
      return YES;
    default:
      return NO;
  }
}
BOOL PresenceObjectTypeIsValidValue(PresenceObjectType value) {
  switch (value) {
    case PresenceObjectTypeFriend:
    case PresenceObjectTypeGroup:
      return YES;
    default:
      return NO;
  }
}
@interface PresencePacket ()
@property PresenceObjectType objecttype;
@property PresenceAtionType actiontype;
@property PresenceType presencetype;
@property (strong) NSString* description;
@end

@implementation PresencePacket

- (BOOL) hasObjecttype {
  return !!hasObjecttype_;
}
- (void) setHasObjecttype:(BOOL) value_ {
  hasObjecttype_ = !!value_;
}
@synthesize objecttype;
- (BOOL) hasActiontype {
  return !!hasActiontype_;
}
- (void) setHasActiontype:(BOOL) value_ {
  hasActiontype_ = !!value_;
}
@synthesize actiontype;
- (BOOL) hasPresencetype {
  return !!hasPresencetype_;
}
- (void) setHasPresencetype:(BOOL) value_ {
  hasPresencetype_ = !!value_;
}
@synthesize presencetype;
- (BOOL) hasDescription {
  return !!hasDescription_;
}
- (void) setHasDescription:(BOOL) value_ {
  hasDescription_ = !!value_;
}
@synthesize description;
- (id) init {
  if ((self = [super init])) {
    self.objecttype = PresenceObjectTypeFriend;
    self.actiontype = PresenceAtionTypeAgreement;
    self.presencetype = PresenceTypeOnLine;
    self.description = @"";
  }
  return self;
}
static PresencePacket* defaultPresencePacketInstance = nil;
+ (void) initialize {
  if (self == [PresencePacket class]) {
    defaultPresencePacketInstance = [[PresencePacket alloc] init];
  }
}
+ (PresencePacket*) defaultInstance {
  return defaultPresencePacketInstance;
}
- (PresencePacket*) defaultInstance {
  return defaultPresencePacketInstance;
}
- (BOOL) isInitialized {
  if (!self.hasObjecttype) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasObjecttype) {
    [output writeEnum:1 value:self.objecttype];
  }
  if (self.hasActiontype) {
    [output writeEnum:2 value:self.actiontype];
  }
  if (self.hasPresencetype) {
    [output writeEnum:3 value:self.presencetype];
  }
  if (self.hasDescription) {
    [output writeString:4 value:self.description];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasObjecttype) {
    size_ += computeEnumSize(1, self.objecttype);
  }
  if (self.hasActiontype) {
    size_ += computeEnumSize(2, self.actiontype);
  }
  if (self.hasPresencetype) {
    size_ += computeEnumSize(3, self.presencetype);
  }
  if (self.hasDescription) {
    size_ += computeStringSize(4, self.description);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PresencePacket*) parseFromData:(NSData*) data {
  return (PresencePacket*)[[[PresencePacket builder] mergeFromData:data] build];
}
+ (PresencePacket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PresencePacket*)[[[PresencePacket builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PresencePacket*) parseFromInputStream:(NSInputStream*) input {
  return (PresencePacket*)[[[PresencePacket builder] mergeFromInputStream:input] build];
}
+ (PresencePacket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PresencePacket*)[[[PresencePacket builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PresencePacket*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PresencePacket*)[[[PresencePacket builder] mergeFromCodedInputStream:input] build];
}
+ (PresencePacket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PresencePacket*)[[[PresencePacket builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PresencePacketBuilder*) builder {
  return [[PresencePacketBuilder alloc] init];
}
+ (PresencePacketBuilder*) builderWithPrototype:(PresencePacket*) prototype {
  return [[PresencePacket builder] mergeFrom:prototype];
}
- (PresencePacketBuilder*) builder {
  return [PresencePacket builder];
}
- (PresencePacketBuilder*) toBuilder {
  return [PresencePacket builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasObjecttype) {
    [output appendFormat:@"%@%@: %@\n", indent, @"objecttype", [NSNumber numberWithInteger:self.objecttype]];
  }
  if (self.hasActiontype) {
    [output appendFormat:@"%@%@: %@\n", indent, @"actiontype", [NSNumber numberWithInteger:self.actiontype]];
  }
  if (self.hasPresencetype) {
    [output appendFormat:@"%@%@: %@\n", indent, @"presencetype", [NSNumber numberWithInteger:self.presencetype]];
  }
  if (self.hasDescription) {
    [output appendFormat:@"%@%@: %@\n", indent, @"description", self.description];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PresencePacket class]]) {
    return NO;
  }
  PresencePacket *otherMessage = other;
  return
      self.hasObjecttype == otherMessage.hasObjecttype &&
      (!self.hasObjecttype || self.objecttype == otherMessage.objecttype) &&
      self.hasActiontype == otherMessage.hasActiontype &&
      (!self.hasActiontype || self.actiontype == otherMessage.actiontype) &&
      self.hasPresencetype == otherMessage.hasPresencetype &&
      (!self.hasPresencetype || self.presencetype == otherMessage.presencetype) &&
      self.hasDescription == otherMessage.hasDescription &&
      (!self.hasDescription || [self.description isEqual:otherMessage.description]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasObjecttype) {
    hashCode = hashCode * 31 + self.objecttype;
  }
  if (self.hasActiontype) {
    hashCode = hashCode * 31 + self.actiontype;
  }
  if (self.hasPresencetype) {
    hashCode = hashCode * 31 + self.presencetype;
  }
  if (self.hasDescription) {
    hashCode = hashCode * 31 + [self.description hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PresencePacketBuilder()
@property (strong) PresencePacket* result;
@end

@implementation PresencePacketBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PresencePacket alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PresencePacketBuilder*) clear {
  self.result = [[PresencePacket alloc] init];
  return self;
}
- (PresencePacketBuilder*) clone {
  return [PresencePacket builderWithPrototype:result];
}
- (PresencePacket*) defaultInstance {
  return [PresencePacket defaultInstance];
}
- (PresencePacket*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PresencePacket*) buildPartial {
  PresencePacket* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PresencePacketBuilder*) mergeFrom:(PresencePacket*) other {
  if (other == [PresencePacket defaultInstance]) {
    return self;
  }
  if (other.hasObjecttype) {
    [self setObjecttype:other.objecttype];
  }
  if (other.hasActiontype) {
    [self setActiontype:other.actiontype];
  }
  if (other.hasPresencetype) {
    [self setPresencetype:other.presencetype];
  }
  if (other.hasDescription) {
    [self setDescription:other.description];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PresencePacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PresencePacketBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        PresenceObjectType value = (PresenceObjectType)[input readEnum];
        if (PresenceObjectTypeIsValidValue(value)) {
          [self setObjecttype:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
      case 16: {
        PresenceAtionType value = (PresenceAtionType)[input readEnum];
        if (PresenceAtionTypeIsValidValue(value)) {
          [self setActiontype:value];
        } else {
          [unknownFields mergeVarintField:2 value:value];
        }
        break;
      }
      case 24: {
        PresenceType value = (PresenceType)[input readEnum];
        if (PresenceTypeIsValidValue(value)) {
          [self setPresencetype:value];
        } else {
          [unknownFields mergeVarintField:3 value:value];
        }
        break;
      }
      case 34: {
        [self setDescription:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasObjecttype {
  return result.hasObjecttype;
}
- (PresenceObjectType) objecttype {
  return result.objecttype;
}
- (PresencePacketBuilder*) setObjecttype:(PresenceObjectType) value {
  result.hasObjecttype = YES;
  result.objecttype = value;
  return self;
}
- (PresencePacketBuilder*) clearObjecttype {
  result.hasObjecttype = NO;
  result.objecttype = PresenceObjectTypeFriend;
  return self;
}
- (BOOL) hasActiontype {
  return result.hasActiontype;
}
- (PresenceAtionType) actiontype {
  return result.actiontype;
}
- (PresencePacketBuilder*) setActiontype:(PresenceAtionType) value {
  result.hasActiontype = YES;
  result.actiontype = value;
  return self;
}
- (PresencePacketBuilder*) clearActiontype {
  result.hasActiontype = NO;
  result.actiontype = PresenceAtionTypeAgreement;
  return self;
}
- (BOOL) hasPresencetype {
  return result.hasPresencetype;
}
- (PresenceType) presencetype {
  return result.presencetype;
}
- (PresencePacketBuilder*) setPresencetype:(PresenceType) value {
  result.hasPresencetype = YES;
  result.presencetype = value;
  return self;
}
- (PresencePacketBuilder*) clearPresencetype {
  result.hasPresencetype = NO;
  result.presencetype = PresenceTypeOnLine;
  return self;
}
- (BOOL) hasDescription {
  return result.hasDescription;
}
- (NSString*) description {
  return result.description;
}
- (PresencePacketBuilder*) setDescription:(NSString*) value {
  result.hasDescription = YES;
  result.description = value;
  return self;
}
- (PresencePacketBuilder*) clearDescription {
  result.hasDescription = NO;
  result.description = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
